/*
 * MUDBASESDK
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@dev.mudbase
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.mudbase.sdk;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.mudbase.sdk.BillingHandleFlutterwaveWebhookRequestDataCustomer;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.mudbase.sdk.JSON;

/**
 * BillingHandleFlutterwaveWebhookRequestData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-18T03:12:24.237846936Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class BillingHandleFlutterwaveWebhookRequestData {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private BigDecimal id;

  public static final String SERIALIZED_NAME_TX_REF = "tx_ref";
  @SerializedName(SERIALIZED_NAME_TX_REF)
  @javax.annotation.Nullable
  private String txRef;

  public static final String SERIALIZED_NAME_FLW_REF = "flw_ref";
  @SerializedName(SERIALIZED_NAME_FLW_REF)
  @javax.annotation.Nullable
  private String flwRef;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  @javax.annotation.Nullable
  private BigDecimal amount;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nullable
  private String currency;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_CUSTOMER = "customer";
  @SerializedName(SERIALIZED_NAME_CUSTOMER)
  @javax.annotation.Nullable
  private BillingHandleFlutterwaveWebhookRequestDataCustomer customer;

  public static final String SERIALIZED_NAME_META = "meta";
  @SerializedName(SERIALIZED_NAME_META)
  @javax.annotation.Nullable
  private Object meta;

  public BillingHandleFlutterwaveWebhookRequestData() {
  }

  public BillingHandleFlutterwaveWebhookRequestData id(@javax.annotation.Nullable BigDecimal id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public BigDecimal getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable BigDecimal id) {
    this.id = id;
  }


  public BillingHandleFlutterwaveWebhookRequestData txRef(@javax.annotation.Nullable String txRef) {
    this.txRef = txRef;
    return this;
  }

  /**
   * Get txRef
   * @return txRef
   */
  @javax.annotation.Nullable
  public String getTxRef() {
    return txRef;
  }

  public void setTxRef(@javax.annotation.Nullable String txRef) {
    this.txRef = txRef;
  }


  public BillingHandleFlutterwaveWebhookRequestData flwRef(@javax.annotation.Nullable String flwRef) {
    this.flwRef = flwRef;
    return this;
  }

  /**
   * Get flwRef
   * @return flwRef
   */
  @javax.annotation.Nullable
  public String getFlwRef() {
    return flwRef;
  }

  public void setFlwRef(@javax.annotation.Nullable String flwRef) {
    this.flwRef = flwRef;
  }


  public BillingHandleFlutterwaveWebhookRequestData amount(@javax.annotation.Nullable BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @javax.annotation.Nullable
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(@javax.annotation.Nullable BigDecimal amount) {
    this.amount = amount;
  }


  public BillingHandleFlutterwaveWebhookRequestData currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public BillingHandleFlutterwaveWebhookRequestData status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public BillingHandleFlutterwaveWebhookRequestData customer(@javax.annotation.Nullable BillingHandleFlutterwaveWebhookRequestDataCustomer customer) {
    this.customer = customer;
    return this;
  }

  /**
   * Get customer
   * @return customer
   */
  @javax.annotation.Nullable
  public BillingHandleFlutterwaveWebhookRequestDataCustomer getCustomer() {
    return customer;
  }

  public void setCustomer(@javax.annotation.Nullable BillingHandleFlutterwaveWebhookRequestDataCustomer customer) {
    this.customer = customer;
  }


  public BillingHandleFlutterwaveWebhookRequestData meta(@javax.annotation.Nullable Object meta) {
    this.meta = meta;
    return this;
  }

  /**
   * orgId, projectId, planId, billingCycle; or isPaymentProcessing true for fiat payment-processing
   * @return meta
   */
  @javax.annotation.Nullable
  public Object getMeta() {
    return meta;
  }

  public void setMeta(@javax.annotation.Nullable Object meta) {
    this.meta = meta;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingHandleFlutterwaveWebhookRequestData billingHandleFlutterwaveWebhookRequestData = (BillingHandleFlutterwaveWebhookRequestData) o;
    return Objects.equals(this.id, billingHandleFlutterwaveWebhookRequestData.id) &&
        Objects.equals(this.txRef, billingHandleFlutterwaveWebhookRequestData.txRef) &&
        Objects.equals(this.flwRef, billingHandleFlutterwaveWebhookRequestData.flwRef) &&
        Objects.equals(this.amount, billingHandleFlutterwaveWebhookRequestData.amount) &&
        Objects.equals(this.currency, billingHandleFlutterwaveWebhookRequestData.currency) &&
        Objects.equals(this.status, billingHandleFlutterwaveWebhookRequestData.status) &&
        Objects.equals(this.customer, billingHandleFlutterwaveWebhookRequestData.customer) &&
        Objects.equals(this.meta, billingHandleFlutterwaveWebhookRequestData.meta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, txRef, flwRef, amount, currency, status, customer, meta);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingHandleFlutterwaveWebhookRequestData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    txRef: ").append(toIndentedString(txRef)).append("\n");
    sb.append("    flwRef: ").append(toIndentedString(flwRef)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "tx_ref", "flw_ref", "amount", "currency", "status", "customer", "meta"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BillingHandleFlutterwaveWebhookRequestData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BillingHandleFlutterwaveWebhookRequestData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BillingHandleFlutterwaveWebhookRequestData is not found in the empty JSON string", BillingHandleFlutterwaveWebhookRequestData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BillingHandleFlutterwaveWebhookRequestData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BillingHandleFlutterwaveWebhookRequestData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("tx_ref") != null && !jsonObj.get("tx_ref").isJsonNull()) && !jsonObj.get("tx_ref").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tx_ref` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tx_ref").toString()));
      }
      if ((jsonObj.get("flw_ref") != null && !jsonObj.get("flw_ref").isJsonNull()) && !jsonObj.get("flw_ref").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `flw_ref` to be a primitive type in the JSON string but got `%s`", jsonObj.get("flw_ref").toString()));
      }
      if ((jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) && !jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `customer`
      if (jsonObj.get("customer") != null && !jsonObj.get("customer").isJsonNull()) {
        BillingHandleFlutterwaveWebhookRequestDataCustomer.validateJsonElement(jsonObj.get("customer"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BillingHandleFlutterwaveWebhookRequestData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BillingHandleFlutterwaveWebhookRequestData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BillingHandleFlutterwaveWebhookRequestData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BillingHandleFlutterwaveWebhookRequestData.class));

       return (TypeAdapter<T>) new TypeAdapter<BillingHandleFlutterwaveWebhookRequestData>() {
           @Override
           public void write(JsonWriter out, BillingHandleFlutterwaveWebhookRequestData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BillingHandleFlutterwaveWebhookRequestData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BillingHandleFlutterwaveWebhookRequestData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BillingHandleFlutterwaveWebhookRequestData
   * @throws IOException if the JSON string is invalid with respect to BillingHandleFlutterwaveWebhookRequestData
   */
  public static BillingHandleFlutterwaveWebhookRequestData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BillingHandleFlutterwaveWebhookRequestData.class);
  }

  /**
   * Convert an instance of BillingHandleFlutterwaveWebhookRequestData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

