/*
 * MUDBASESDK
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.7
 * Contact: support@mudbase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mudbase.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mudbase.sdk.JSON;

/**
 * ApiProjectsProjectIdKybSessionsPostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-02T03:16:38.770132325Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class ApiProjectsProjectIdKybSessionsPostRequest {
  public static final String SERIALIZED_NAME_WORKFLOW_ID = "workflowId";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_ID)
  @javax.annotation.Nullable
  private String workflowId;

  public static final String SERIALIZED_NAME_VENDOR_BUSINESS_ID = "vendorBusinessId";
  @SerializedName(SERIALIZED_NAME_VENDOR_BUSINESS_ID)
  @javax.annotation.Nullable
  private String vendorBusinessId;

  public static final String SERIALIZED_NAME_VENDOR_DATA = "vendorData";
  @SerializedName(SERIALIZED_NAME_VENDOR_DATA)
  @javax.annotation.Nullable
  private String vendorData;

  public static final String SERIALIZED_NAME_CALLBACK = "callback";
  @SerializedName(SERIALIZED_NAME_CALLBACK)
  @javax.annotation.Nullable
  private String callback;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  @javax.annotation.Nullable
  private String language;

  public ApiProjectsProjectIdKybSessionsPostRequest() {
  }

  public ApiProjectsProjectIdKybSessionsPostRequest workflowId(@javax.annotation.Nullable String workflowId) {
    this.workflowId = workflowId;
    return this;
  }

  /**
   * Overrides the organization&#39;s default KYB workflow.
   * @return workflowId
   */
  @javax.annotation.Nullable
  public String getWorkflowId() {
    return workflowId;
  }

  public void setWorkflowId(@javax.annotation.Nullable String workflowId) {
    this.workflowId = workflowId;
  }


  public ApiProjectsProjectIdKybSessionsPostRequest vendorBusinessId(@javax.annotation.Nullable String vendorBusinessId) {
    this.vendorBusinessId = vendorBusinessId;
    return this;
  }

  /**
   * Your own identifier for the business being verified.
   * @return vendorBusinessId
   */
  @javax.annotation.Nullable
  public String getVendorBusinessId() {
    return vendorBusinessId;
  }

  public void setVendorBusinessId(@javax.annotation.Nullable String vendorBusinessId) {
    this.vendorBusinessId = vendorBusinessId;
  }


  public ApiProjectsProjectIdKybSessionsPostRequest vendorData(@javax.annotation.Nullable String vendorData) {
    this.vendorData = vendorData;
    return this;
  }

  /**
   * Arbitrary reference echoed back on webhooks.
   * @return vendorData
   */
  @javax.annotation.Nullable
  public String getVendorData() {
    return vendorData;
  }

  public void setVendorData(@javax.annotation.Nullable String vendorData) {
    this.vendorData = vendorData;
  }


  public ApiProjectsProjectIdKybSessionsPostRequest callback(@javax.annotation.Nullable String callback) {
    this.callback = callback;
    return this;
  }

  /**
   * Where to redirect the business user after the hosted flow.
   * @return callback
   */
  @javax.annotation.Nullable
  public String getCallback() {
    return callback;
  }

  public void setCallback(@javax.annotation.Nullable String callback) {
    this.callback = callback;
  }


  public ApiProjectsProjectIdKybSessionsPostRequest language(@javax.annotation.Nullable String language) {
    this.language = language;
    return this;
  }

  /**
   * Get language
   * @return language
   */
  @javax.annotation.Nullable
  public String getLanguage() {
    return language;
  }

  public void setLanguage(@javax.annotation.Nullable String language) {
    this.language = language;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiProjectsProjectIdKybSessionsPostRequest apiProjectsProjectIdKybSessionsPostRequest = (ApiProjectsProjectIdKybSessionsPostRequest) o;
    return Objects.equals(this.workflowId, apiProjectsProjectIdKybSessionsPostRequest.workflowId) &&
        Objects.equals(this.vendorBusinessId, apiProjectsProjectIdKybSessionsPostRequest.vendorBusinessId) &&
        Objects.equals(this.vendorData, apiProjectsProjectIdKybSessionsPostRequest.vendorData) &&
        Objects.equals(this.callback, apiProjectsProjectIdKybSessionsPostRequest.callback) &&
        Objects.equals(this.language, apiProjectsProjectIdKybSessionsPostRequest.language);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workflowId, vendorBusinessId, vendorData, callback, language);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiProjectsProjectIdKybSessionsPostRequest {\n");
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("    vendorBusinessId: ").append(toIndentedString(vendorBusinessId)).append("\n");
    sb.append("    vendorData: ").append(toIndentedString(vendorData)).append("\n");
    sb.append("    callback: ").append(toIndentedString(callback)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("workflowId", "vendorBusinessId", "vendorData", "callback", "language"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ApiProjectsProjectIdKybSessionsPostRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ApiProjectsProjectIdKybSessionsPostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ApiProjectsProjectIdKybSessionsPostRequest is not found in the empty JSON string", ApiProjectsProjectIdKybSessionsPostRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ApiProjectsProjectIdKybSessionsPostRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ApiProjectsProjectIdKybSessionsPostRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("workflowId") != null && !jsonObj.get("workflowId").isJsonNull()) && !jsonObj.get("workflowId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `workflowId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("workflowId").toString()));
      }
      if ((jsonObj.get("vendorBusinessId") != null && !jsonObj.get("vendorBusinessId").isJsonNull()) && !jsonObj.get("vendorBusinessId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `vendorBusinessId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vendorBusinessId").toString()));
      }
      if ((jsonObj.get("vendorData") != null && !jsonObj.get("vendorData").isJsonNull()) && !jsonObj.get("vendorData").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `vendorData` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vendorData").toString()));
      }
      if ((jsonObj.get("callback") != null && !jsonObj.get("callback").isJsonNull()) && !jsonObj.get("callback").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `callback` to be a primitive type in the JSON string but got `%s`", jsonObj.get("callback").toString()));
      }
      if ((jsonObj.get("language") != null && !jsonObj.get("language").isJsonNull()) && !jsonObj.get("language").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `language` to be a primitive type in the JSON string but got `%s`", jsonObj.get("language").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApiProjectsProjectIdKybSessionsPostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApiProjectsProjectIdKybSessionsPostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApiProjectsProjectIdKybSessionsPostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApiProjectsProjectIdKybSessionsPostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ApiProjectsProjectIdKybSessionsPostRequest>() {
           @Override
           public void write(JsonWriter out, ApiProjectsProjectIdKybSessionsPostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApiProjectsProjectIdKybSessionsPostRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ApiProjectsProjectIdKybSessionsPostRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ApiProjectsProjectIdKybSessionsPostRequest
   * @throws IOException if the JSON string is invalid with respect to ApiProjectsProjectIdKybSessionsPostRequest
   */
  public static ApiProjectsProjectIdKybSessionsPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApiProjectsProjectIdKybSessionsPostRequest.class);
  }

  /**
   * Convert an instance of ApiProjectsProjectIdKybSessionsPostRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

