/*
 * MUDBASESDK
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.8
 * Contact: support@mudbase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mudbase.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mudbase.sdk.JSON;

/**
 * CheckUserPresence200ResponsePresenceValue
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-02T03:45:44.663985817Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class CheckUserPresence200ResponsePresenceValue {
  public static final String SERIALIZED_NAME_ONLINE = "online";
  @SerializedName(SERIALIZED_NAME_ONLINE)
  @javax.annotation.Nullable
  private Boolean online;

  public static final String SERIALIZED_NAME_LAST_SEEN = "lastSeen";
  @SerializedName(SERIALIZED_NAME_LAST_SEEN)
  @javax.annotation.Nullable
  private OffsetDateTime lastSeen;

  public CheckUserPresence200ResponsePresenceValue() {
  }

  public CheckUserPresence200ResponsePresenceValue online(@javax.annotation.Nullable Boolean online) {
    this.online = online;
    return this;
  }

  /**
   * Get online
   * @return online
   */
  @javax.annotation.Nullable
  public Boolean getOnline() {
    return online;
  }

  public void setOnline(@javax.annotation.Nullable Boolean online) {
    this.online = online;
  }


  public CheckUserPresence200ResponsePresenceValue lastSeen(@javax.annotation.Nullable OffsetDateTime lastSeen) {
    this.lastSeen = lastSeen;
    return this;
  }

  /**
   * Get lastSeen
   * @return lastSeen
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastSeen() {
    return lastSeen;
  }

  public void setLastSeen(@javax.annotation.Nullable OffsetDateTime lastSeen) {
    this.lastSeen = lastSeen;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckUserPresence200ResponsePresenceValue checkUserPresence200ResponsePresenceValue = (CheckUserPresence200ResponsePresenceValue) o;
    return Objects.equals(this.online, checkUserPresence200ResponsePresenceValue.online) &&
        Objects.equals(this.lastSeen, checkUserPresence200ResponsePresenceValue.lastSeen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(online, lastSeen);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckUserPresence200ResponsePresenceValue {\n");
    sb.append("    online: ").append(toIndentedString(online)).append("\n");
    sb.append("    lastSeen: ").append(toIndentedString(lastSeen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("online", "lastSeen"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CheckUserPresence200ResponsePresenceValue
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CheckUserPresence200ResponsePresenceValue.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CheckUserPresence200ResponsePresenceValue is not found in the empty JSON string", CheckUserPresence200ResponsePresenceValue.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CheckUserPresence200ResponsePresenceValue.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CheckUserPresence200ResponsePresenceValue` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CheckUserPresence200ResponsePresenceValue.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CheckUserPresence200ResponsePresenceValue' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CheckUserPresence200ResponsePresenceValue> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CheckUserPresence200ResponsePresenceValue.class));

       return (TypeAdapter<T>) new TypeAdapter<CheckUserPresence200ResponsePresenceValue>() {
           @Override
           public void write(JsonWriter out, CheckUserPresence200ResponsePresenceValue value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CheckUserPresence200ResponsePresenceValue read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CheckUserPresence200ResponsePresenceValue given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CheckUserPresence200ResponsePresenceValue
   * @throws IOException if the JSON string is invalid with respect to CheckUserPresence200ResponsePresenceValue
   */
  public static CheckUserPresence200ResponsePresenceValue fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CheckUserPresence200ResponsePresenceValue.class);
  }

  /**
   * Convert an instance of CheckUserPresence200ResponsePresenceValue to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

