/*
 * MUDBASESDK
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.14
 * Contact: support@mudbase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mudbase.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mudbase.sdk.model.CreatePlanRequestLimitsCustomLimitsInner;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mudbase.sdk.JSON;

/**
 * Plan caps; null or omitted fields mean unlimited where applicable.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-09T22:15:44.281428325Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class CreatePlanRequestLimits {
  public static final String SERIALIZED_NAME_API_CALLS = "apiCalls";
  @SerializedName(SERIALIZED_NAME_API_CALLS)
  @javax.annotation.Nullable
  private BigDecimal apiCalls;

  public static final String SERIALIZED_NAME_STORAGE = "storage";
  @SerializedName(SERIALIZED_NAME_STORAGE)
  @javax.annotation.Nullable
  private BigDecimal storage;

  public static final String SERIALIZED_NAME_BANDWIDTH = "bandwidth";
  @SerializedName(SERIALIZED_NAME_BANDWIDTH)
  @javax.annotation.Nullable
  private BigDecimal bandwidth;

  public static final String SERIALIZED_NAME_USERS = "users";
  @SerializedName(SERIALIZED_NAME_USERS)
  @javax.annotation.Nullable
  private BigDecimal users;

  public static final String SERIALIZED_NAME_CUSTOM_LIMITS = "customLimits";
  @SerializedName(SERIALIZED_NAME_CUSTOM_LIMITS)
  @javax.annotation.Nullable
  private List<CreatePlanRequestLimitsCustomLimitsInner> customLimits = new ArrayList<>();

  public CreatePlanRequestLimits() {
  }

  public CreatePlanRequestLimits apiCalls(@javax.annotation.Nullable BigDecimal apiCalls) {
    this.apiCalls = apiCalls;
    return this;
  }

  /**
   * Get apiCalls
   * @return apiCalls
   */
  @javax.annotation.Nullable
  public BigDecimal getApiCalls() {
    return apiCalls;
  }

  public void setApiCalls(@javax.annotation.Nullable BigDecimal apiCalls) {
    this.apiCalls = apiCalls;
  }


  public CreatePlanRequestLimits storage(@javax.annotation.Nullable BigDecimal storage) {
    this.storage = storage;
    return this;
  }

  /**
   * Get storage
   * @return storage
   */
  @javax.annotation.Nullable
  public BigDecimal getStorage() {
    return storage;
  }

  public void setStorage(@javax.annotation.Nullable BigDecimal storage) {
    this.storage = storage;
  }


  public CreatePlanRequestLimits bandwidth(@javax.annotation.Nullable BigDecimal bandwidth) {
    this.bandwidth = bandwidth;
    return this;
  }

  /**
   * Get bandwidth
   * @return bandwidth
   */
  @javax.annotation.Nullable
  public BigDecimal getBandwidth() {
    return bandwidth;
  }

  public void setBandwidth(@javax.annotation.Nullable BigDecimal bandwidth) {
    this.bandwidth = bandwidth;
  }


  public CreatePlanRequestLimits users(@javax.annotation.Nullable BigDecimal users) {
    this.users = users;
    return this;
  }

  /**
   * Get users
   * @return users
   */
  @javax.annotation.Nullable
  public BigDecimal getUsers() {
    return users;
  }

  public void setUsers(@javax.annotation.Nullable BigDecimal users) {
    this.users = users;
  }


  public CreatePlanRequestLimits customLimits(@javax.annotation.Nullable List<CreatePlanRequestLimitsCustomLimitsInner> customLimits) {
    this.customLimits = customLimits;
    return this;
  }

  public CreatePlanRequestLimits addCustomLimitsItem(CreatePlanRequestLimitsCustomLimitsInner customLimitsItem) {
    if (this.customLimits == null) {
      this.customLimits = new ArrayList<>();
    }
    this.customLimits.add(customLimitsItem);
    return this;
  }

  /**
   * Get customLimits
   * @return customLimits
   */
  @javax.annotation.Nullable
  public List<CreatePlanRequestLimitsCustomLimitsInner> getCustomLimits() {
    return customLimits;
  }

  public void setCustomLimits(@javax.annotation.Nullable List<CreatePlanRequestLimitsCustomLimitsInner> customLimits) {
    this.customLimits = customLimits;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePlanRequestLimits createPlanRequestLimits = (CreatePlanRequestLimits) o;
    return Objects.equals(this.apiCalls, createPlanRequestLimits.apiCalls) &&
        Objects.equals(this.storage, createPlanRequestLimits.storage) &&
        Objects.equals(this.bandwidth, createPlanRequestLimits.bandwidth) &&
        Objects.equals(this.users, createPlanRequestLimits.users) &&
        Objects.equals(this.customLimits, createPlanRequestLimits.customLimits);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiCalls, storage, bandwidth, users, customLimits);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePlanRequestLimits {\n");
    sb.append("    apiCalls: ").append(toIndentedString(apiCalls)).append("\n");
    sb.append("    storage: ").append(toIndentedString(storage)).append("\n");
    sb.append("    bandwidth: ").append(toIndentedString(bandwidth)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("    customLimits: ").append(toIndentedString(customLimits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("apiCalls", "storage", "bandwidth", "users", "customLimits"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreatePlanRequestLimits
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreatePlanRequestLimits.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreatePlanRequestLimits is not found in the empty JSON string", CreatePlanRequestLimits.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreatePlanRequestLimits.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreatePlanRequestLimits` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("customLimits") != null && !jsonObj.get("customLimits").isJsonNull()) {
        JsonArray jsonArraycustomLimits = jsonObj.getAsJsonArray("customLimits");
        if (jsonArraycustomLimits != null) {
          // ensure the json data is an array
          if (!jsonObj.get("customLimits").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `customLimits` to be an array in the JSON string but got `%s`", jsonObj.get("customLimits").toString()));
          }

          // validate the optional field `customLimits` (array)
          for (int i = 0; i < jsonArraycustomLimits.size(); i++) {
            CreatePlanRequestLimitsCustomLimitsInner.validateJsonElement(jsonArraycustomLimits.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreatePlanRequestLimits.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreatePlanRequestLimits' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreatePlanRequestLimits> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreatePlanRequestLimits.class));

       return (TypeAdapter<T>) new TypeAdapter<CreatePlanRequestLimits>() {
           @Override
           public void write(JsonWriter out, CreatePlanRequestLimits value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreatePlanRequestLimits read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreatePlanRequestLimits given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreatePlanRequestLimits
   * @throws IOException if the JSON string is invalid with respect to CreatePlanRequestLimits
   */
  public static CreatePlanRequestLimits fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreatePlanRequestLimits.class);
  }

  /**
   * Convert an instance of CreatePlanRequestLimits to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

