/*
 * MUDBASESDK
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.4
 * Contact: support@mudbase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mudbase.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mudbase.sdk.JSON;

/**
 * FunctionExecutionStatusResponseDataLogs
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-02T02:48:22.795883382Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class FunctionExecutionStatusResponseDataLogs {
  public static final String SERIALIZED_NAME_STDOUT = "stdout";
  @SerializedName(SERIALIZED_NAME_STDOUT)
  @javax.annotation.Nullable
  private String stdout;

  public static final String SERIALIZED_NAME_STDERR = "stderr";
  @SerializedName(SERIALIZED_NAME_STDERR)
  @javax.annotation.Nullable
  private String stderr;

  public static final String SERIALIZED_NAME_TRUNCATED = "truncated";
  @SerializedName(SERIALIZED_NAME_TRUNCATED)
  @javax.annotation.Nullable
  private Boolean truncated;

  public static final String SERIALIZED_NAME_BYTES = "bytes";
  @SerializedName(SERIALIZED_NAME_BYTES)
  @javax.annotation.Nullable
  private Integer bytes;

  public FunctionExecutionStatusResponseDataLogs() {
  }

  public FunctionExecutionStatusResponseDataLogs stdout(@javax.annotation.Nullable String stdout) {
    this.stdout = stdout;
    return this;
  }

  /**
   * Get stdout
   * @return stdout
   */
  @javax.annotation.Nullable
  public String getStdout() {
    return stdout;
  }

  public void setStdout(@javax.annotation.Nullable String stdout) {
    this.stdout = stdout;
  }


  public FunctionExecutionStatusResponseDataLogs stderr(@javax.annotation.Nullable String stderr) {
    this.stderr = stderr;
    return this;
  }

  /**
   * Get stderr
   * @return stderr
   */
  @javax.annotation.Nullable
  public String getStderr() {
    return stderr;
  }

  public void setStderr(@javax.annotation.Nullable String stderr) {
    this.stderr = stderr;
  }


  public FunctionExecutionStatusResponseDataLogs truncated(@javax.annotation.Nullable Boolean truncated) {
    this.truncated = truncated;
    return this;
  }

  /**
   * Get truncated
   * @return truncated
   */
  @javax.annotation.Nullable
  public Boolean getTruncated() {
    return truncated;
  }

  public void setTruncated(@javax.annotation.Nullable Boolean truncated) {
    this.truncated = truncated;
  }


  public FunctionExecutionStatusResponseDataLogs bytes(@javax.annotation.Nullable Integer bytes) {
    this.bytes = bytes;
    return this;
  }

  /**
   * Get bytes
   * @return bytes
   */
  @javax.annotation.Nullable
  public Integer getBytes() {
    return bytes;
  }

  public void setBytes(@javax.annotation.Nullable Integer bytes) {
    this.bytes = bytes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FunctionExecutionStatusResponseDataLogs functionExecutionStatusResponseDataLogs = (FunctionExecutionStatusResponseDataLogs) o;
    return Objects.equals(this.stdout, functionExecutionStatusResponseDataLogs.stdout) &&
        Objects.equals(this.stderr, functionExecutionStatusResponseDataLogs.stderr) &&
        Objects.equals(this.truncated, functionExecutionStatusResponseDataLogs.truncated) &&
        Objects.equals(this.bytes, functionExecutionStatusResponseDataLogs.bytes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stdout, stderr, truncated, bytes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FunctionExecutionStatusResponseDataLogs {\n");
    sb.append("    stdout: ").append(toIndentedString(stdout)).append("\n");
    sb.append("    stderr: ").append(toIndentedString(stderr)).append("\n");
    sb.append("    truncated: ").append(toIndentedString(truncated)).append("\n");
    sb.append("    bytes: ").append(toIndentedString(bytes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("stdout", "stderr", "truncated", "bytes"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FunctionExecutionStatusResponseDataLogs
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FunctionExecutionStatusResponseDataLogs.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in FunctionExecutionStatusResponseDataLogs is not found in the empty JSON string", FunctionExecutionStatusResponseDataLogs.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FunctionExecutionStatusResponseDataLogs.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `FunctionExecutionStatusResponseDataLogs` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("stdout") != null && !jsonObj.get("stdout").isJsonNull()) && !jsonObj.get("stdout").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `stdout` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stdout").toString()));
      }
      if ((jsonObj.get("stderr") != null && !jsonObj.get("stderr").isJsonNull()) && !jsonObj.get("stderr").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `stderr` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stderr").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FunctionExecutionStatusResponseDataLogs.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FunctionExecutionStatusResponseDataLogs' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FunctionExecutionStatusResponseDataLogs> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FunctionExecutionStatusResponseDataLogs.class));

       return (TypeAdapter<T>) new TypeAdapter<FunctionExecutionStatusResponseDataLogs>() {
           @Override
           public void write(JsonWriter out, FunctionExecutionStatusResponseDataLogs value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FunctionExecutionStatusResponseDataLogs read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FunctionExecutionStatusResponseDataLogs given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FunctionExecutionStatusResponseDataLogs
   * @throws IOException if the JSON string is invalid with respect to FunctionExecutionStatusResponseDataLogs
   */
  public static FunctionExecutionStatusResponseDataLogs fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FunctionExecutionStatusResponseDataLogs.class);
  }

  /**
   * Convert an instance of FunctionExecutionStatusResponseDataLogs to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

