/*
 * MUDBASESDK
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.15
 * Contact: support@mudbase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mudbase.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mudbase.sdk.model.GetSearchAnalytics200ResponseTopQueriesInner;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mudbase.sdk.JSON;

/**
 * GetSearchAnalytics200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-10T11:48:57.705617248Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class GetSearchAnalytics200Response {
  public static final String SERIALIZED_NAME_TOTAL_SEARCHES = "totalSearches";
  @SerializedName(SERIALIZED_NAME_TOTAL_SEARCHES)
  @javax.annotation.Nullable
  private Integer totalSearches;

  public static final String SERIALIZED_NAME_TOP_QUERIES = "topQueries";
  @SerializedName(SERIALIZED_NAME_TOP_QUERIES)
  @javax.annotation.Nullable
  private List<GetSearchAnalytics200ResponseTopQueriesInner> topQueries = new ArrayList<>();

  public static final String SERIALIZED_NAME_SEARCHES_BY_COLLECTION = "searchesByCollection";
  @SerializedName(SERIALIZED_NAME_SEARCHES_BY_COLLECTION)
  @javax.annotation.Nullable
  private Object searchesByCollection;

  public static final String SERIALIZED_NAME_AVERAGE_RESPONSE_TIME = "averageResponseTime";
  @SerializedName(SERIALIZED_NAME_AVERAGE_RESPONSE_TIME)
  @javax.annotation.Nullable
  private BigDecimal averageResponseTime;

  public GetSearchAnalytics200Response() {
  }

  public GetSearchAnalytics200Response totalSearches(@javax.annotation.Nullable Integer totalSearches) {
    this.totalSearches = totalSearches;
    return this;
  }

  /**
   * Get totalSearches
   * @return totalSearches
   */
  @javax.annotation.Nullable
  public Integer getTotalSearches() {
    return totalSearches;
  }

  public void setTotalSearches(@javax.annotation.Nullable Integer totalSearches) {
    this.totalSearches = totalSearches;
  }


  public GetSearchAnalytics200Response topQueries(@javax.annotation.Nullable List<GetSearchAnalytics200ResponseTopQueriesInner> topQueries) {
    this.topQueries = topQueries;
    return this;
  }

  public GetSearchAnalytics200Response addTopQueriesItem(GetSearchAnalytics200ResponseTopQueriesInner topQueriesItem) {
    if (this.topQueries == null) {
      this.topQueries = new ArrayList<>();
    }
    this.topQueries.add(topQueriesItem);
    return this;
  }

  /**
   * Get topQueries
   * @return topQueries
   */
  @javax.annotation.Nullable
  public List<GetSearchAnalytics200ResponseTopQueriesInner> getTopQueries() {
    return topQueries;
  }

  public void setTopQueries(@javax.annotation.Nullable List<GetSearchAnalytics200ResponseTopQueriesInner> topQueries) {
    this.topQueries = topQueries;
  }


  public GetSearchAnalytics200Response searchesByCollection(@javax.annotation.Nullable Object searchesByCollection) {
    this.searchesByCollection = searchesByCollection;
    return this;
  }

  /**
   * Get searchesByCollection
   * @return searchesByCollection
   */
  @javax.annotation.Nullable
  public Object getSearchesByCollection() {
    return searchesByCollection;
  }

  public void setSearchesByCollection(@javax.annotation.Nullable Object searchesByCollection) {
    this.searchesByCollection = searchesByCollection;
  }


  public GetSearchAnalytics200Response averageResponseTime(@javax.annotation.Nullable BigDecimal averageResponseTime) {
    this.averageResponseTime = averageResponseTime;
    return this;
  }

  /**
   * Get averageResponseTime
   * @return averageResponseTime
   */
  @javax.annotation.Nullable
  public BigDecimal getAverageResponseTime() {
    return averageResponseTime;
  }

  public void setAverageResponseTime(@javax.annotation.Nullable BigDecimal averageResponseTime) {
    this.averageResponseTime = averageResponseTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSearchAnalytics200Response getSearchAnalytics200Response = (GetSearchAnalytics200Response) o;
    return Objects.equals(this.totalSearches, getSearchAnalytics200Response.totalSearches) &&
        Objects.equals(this.topQueries, getSearchAnalytics200Response.topQueries) &&
        Objects.equals(this.searchesByCollection, getSearchAnalytics200Response.searchesByCollection) &&
        Objects.equals(this.averageResponseTime, getSearchAnalytics200Response.averageResponseTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalSearches, topQueries, searchesByCollection, averageResponseTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSearchAnalytics200Response {\n");
    sb.append("    totalSearches: ").append(toIndentedString(totalSearches)).append("\n");
    sb.append("    topQueries: ").append(toIndentedString(topQueries)).append("\n");
    sb.append("    searchesByCollection: ").append(toIndentedString(searchesByCollection)).append("\n");
    sb.append("    averageResponseTime: ").append(toIndentedString(averageResponseTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("totalSearches", "topQueries", "searchesByCollection", "averageResponseTime"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetSearchAnalytics200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetSearchAnalytics200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetSearchAnalytics200Response is not found in the empty JSON string", GetSearchAnalytics200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetSearchAnalytics200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetSearchAnalytics200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("topQueries") != null && !jsonObj.get("topQueries").isJsonNull()) {
        JsonArray jsonArraytopQueries = jsonObj.getAsJsonArray("topQueries");
        if (jsonArraytopQueries != null) {
          // ensure the json data is an array
          if (!jsonObj.get("topQueries").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `topQueries` to be an array in the JSON string but got `%s`", jsonObj.get("topQueries").toString()));
          }

          // validate the optional field `topQueries` (array)
          for (int i = 0; i < jsonArraytopQueries.size(); i++) {
            GetSearchAnalytics200ResponseTopQueriesInner.validateJsonElement(jsonArraytopQueries.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetSearchAnalytics200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetSearchAnalytics200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetSearchAnalytics200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetSearchAnalytics200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<GetSearchAnalytics200Response>() {
           @Override
           public void write(JsonWriter out, GetSearchAnalytics200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetSearchAnalytics200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetSearchAnalytics200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetSearchAnalytics200Response
   * @throws IOException if the JSON string is invalid with respect to GetSearchAnalytics200Response
   */
  public static GetSearchAnalytics200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetSearchAnalytics200Response.class);
  }

  /**
   * Convert an instance of GetSearchAnalytics200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

