/*
 * MUDBASESDK
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave for fiat (platform subscriptions and payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.12
 * Contact: support@mudbase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mudbase.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mudbase.sdk.JSON;

/**
 * Feature toggles for signup behavior (not per-role approval flags).
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T01:32:59.737390176Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class MultiRoleUpdateSettingsRequestSettings {
  public static final String SERIALIZED_NAME_ALLOW_MULTIPLE_ROLES = "allowMultipleRoles";
  @SerializedName(SERIALIZED_NAME_ALLOW_MULTIPLE_ROLES)
  @javax.annotation.Nullable
  private Boolean allowMultipleRoles;

  public static final String SERIALIZED_NAME_REQUIRE_ROLE_SELECTION = "requireRoleSelection";
  @SerializedName(SERIALIZED_NAME_REQUIRE_ROLE_SELECTION)
  @javax.annotation.Nullable
  private Boolean requireRoleSelection;

  public static final String SERIALIZED_NAME_AUTO_ASSIGN_DEFAULT = "autoAssignDefault";
  @SerializedName(SERIALIZED_NAME_AUTO_ASSIGN_DEFAULT)
  @javax.annotation.Nullable
  private Boolean autoAssignDefault;

  public static final String SERIALIZED_NAME_DATA_OWNER_FIELD = "dataOwnerField";
  @SerializedName(SERIALIZED_NAME_DATA_OWNER_FIELD)
  @javax.annotation.Nullable
  private String dataOwnerField = "createdBy";

  public MultiRoleUpdateSettingsRequestSettings() {
  }

  public MultiRoleUpdateSettingsRequestSettings allowMultipleRoles(@javax.annotation.Nullable Boolean allowMultipleRoles) {
    this.allowMultipleRoles = allowMultipleRoles;
    return this;
  }

  /**
   * Whether an end user may hold multiple app roles.
   * @return allowMultipleRoles
   */
  @javax.annotation.Nullable
  public Boolean getAllowMultipleRoles() {
    return allowMultipleRoles;
  }

  public void setAllowMultipleRoles(@javax.annotation.Nullable Boolean allowMultipleRoles) {
    this.allowMultipleRoles = allowMultipleRoles;
  }


  public MultiRoleUpdateSettingsRequestSettings requireRoleSelection(@javax.annotation.Nullable Boolean requireRoleSelection) {
    this.requireRoleSelection = requireRoleSelection;
    return this;
  }

  /**
   * If true, signup must pick a role; if false and &#x60;autoAssignDefault&#x60; is true, &#x60;defaultRole&#x60; is used when omitted.
   * @return requireRoleSelection
   */
  @javax.annotation.Nullable
  public Boolean getRequireRoleSelection() {
    return requireRoleSelection;
  }

  public void setRequireRoleSelection(@javax.annotation.Nullable Boolean requireRoleSelection) {
    this.requireRoleSelection = requireRoleSelection;
  }


  public MultiRoleUpdateSettingsRequestSettings autoAssignDefault(@javax.annotation.Nullable Boolean autoAssignDefault) {
    this.autoAssignDefault = autoAssignDefault;
    return this;
  }

  /**
   * When true, assigns &#x60;defaultRole&#x60; when the client does not specify a role at signup.
   * @return autoAssignDefault
   */
  @javax.annotation.Nullable
  public Boolean getAutoAssignDefault() {
    return autoAssignDefault;
  }

  public void setAutoAssignDefault(@javax.annotation.Nullable Boolean autoAssignDefault) {
    this.autoAssignDefault = autoAssignDefault;
  }


  public MultiRoleUpdateSettingsRequestSettings dataOwnerField(@javax.annotation.Nullable String dataOwnerField) {
    this.dataOwnerField = dataOwnerField;
    return this;
  }

  /**
   * Default document field for &#x60;dataScope: own&#x60; (e.g. &#x60;createdBy&#x60;, &#x60;userId&#x60;).
   * @return dataOwnerField
   */
  @javax.annotation.Nullable
  public String getDataOwnerField() {
    return dataOwnerField;
  }

  public void setDataOwnerField(@javax.annotation.Nullable String dataOwnerField) {
    this.dataOwnerField = dataOwnerField;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiRoleUpdateSettingsRequestSettings multiRoleUpdateSettingsRequestSettings = (MultiRoleUpdateSettingsRequestSettings) o;
    return Objects.equals(this.allowMultipleRoles, multiRoleUpdateSettingsRequestSettings.allowMultipleRoles) &&
        Objects.equals(this.requireRoleSelection, multiRoleUpdateSettingsRequestSettings.requireRoleSelection) &&
        Objects.equals(this.autoAssignDefault, multiRoleUpdateSettingsRequestSettings.autoAssignDefault) &&
        Objects.equals(this.dataOwnerField, multiRoleUpdateSettingsRequestSettings.dataOwnerField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowMultipleRoles, requireRoleSelection, autoAssignDefault, dataOwnerField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiRoleUpdateSettingsRequestSettings {\n");
    sb.append("    allowMultipleRoles: ").append(toIndentedString(allowMultipleRoles)).append("\n");
    sb.append("    requireRoleSelection: ").append(toIndentedString(requireRoleSelection)).append("\n");
    sb.append("    autoAssignDefault: ").append(toIndentedString(autoAssignDefault)).append("\n");
    sb.append("    dataOwnerField: ").append(toIndentedString(dataOwnerField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("allowMultipleRoles", "requireRoleSelection", "autoAssignDefault", "dataOwnerField"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MultiRoleUpdateSettingsRequestSettings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MultiRoleUpdateSettingsRequestSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MultiRoleUpdateSettingsRequestSettings is not found in the empty JSON string", MultiRoleUpdateSettingsRequestSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MultiRoleUpdateSettingsRequestSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MultiRoleUpdateSettingsRequestSettings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("dataOwnerField") != null && !jsonObj.get("dataOwnerField").isJsonNull()) && !jsonObj.get("dataOwnerField").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dataOwnerField` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataOwnerField").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MultiRoleUpdateSettingsRequestSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MultiRoleUpdateSettingsRequestSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MultiRoleUpdateSettingsRequestSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MultiRoleUpdateSettingsRequestSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<MultiRoleUpdateSettingsRequestSettings>() {
           @Override
           public void write(JsonWriter out, MultiRoleUpdateSettingsRequestSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MultiRoleUpdateSettingsRequestSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MultiRoleUpdateSettingsRequestSettings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MultiRoleUpdateSettingsRequestSettings
   * @throws IOException if the JSON string is invalid with respect to MultiRoleUpdateSettingsRequestSettings
   */
  public static MultiRoleUpdateSettingsRequestSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MultiRoleUpdateSettingsRequestSettings.class);
  }

  /**
   * Convert an instance of MultiRoleUpdateSettingsRequestSettings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

