/*
 * MUDBASESDK
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 
 *
 * The version of the OpenAPI document: 1.3.9
 * Contact: support@mudbase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mudbase.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mudbase.sdk.JSON;

/**
 * ProjectSmsByoPublic
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-02T04:00:38.804133960Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class ProjectSmsByoPublic {
  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  /**
   * Gets or Sets provider
   */
  @JsonAdapter(ProviderEnum.Adapter.class)
  public enum ProviderEnum {
    TWILIO("twilio"),
    
    TERMII("termii"),
    
    AFRICASTALKING("africastalking"),
    
    NONE("none");

    private String value;

    ProviderEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ProviderEnum fromValue(String value) {
      for (ProviderEnum b : ProviderEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ProviderEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProviderEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ProviderEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ProviderEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ProviderEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  @javax.annotation.Nullable
  private ProviderEnum provider;

  public static final String SERIALIZED_NAME_DEFAULT_FROM = "defaultFrom";
  @SerializedName(SERIALIZED_NAME_DEFAULT_FROM)
  @javax.annotation.Nullable
  private String defaultFrom;

  public static final String SERIALIZED_NAME_HAS_CREDENTIALS = "hasCredentials";
  @SerializedName(SERIALIZED_NAME_HAS_CREDENTIALS)
  @javax.annotation.Nullable
  private Boolean hasCredentials;

  public ProjectSmsByoPublic() {
  }

  public ProjectSmsByoPublic enabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public ProjectSmsByoPublic provider(@javax.annotation.Nullable ProviderEnum provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nullable
  public ProviderEnum getProvider() {
    return provider;
  }

  public void setProvider(@javax.annotation.Nullable ProviderEnum provider) {
    this.provider = provider;
  }


  public ProjectSmsByoPublic defaultFrom(@javax.annotation.Nullable String defaultFrom) {
    this.defaultFrom = defaultFrom;
    return this;
  }

  /**
   * Get defaultFrom
   * @return defaultFrom
   */
  @javax.annotation.Nullable
  public String getDefaultFrom() {
    return defaultFrom;
  }

  public void setDefaultFrom(@javax.annotation.Nullable String defaultFrom) {
    this.defaultFrom = defaultFrom;
  }


  public ProjectSmsByoPublic hasCredentials(@javax.annotation.Nullable Boolean hasCredentials) {
    this.hasCredentials = hasCredentials;
    return this;
  }

  /**
   * Get hasCredentials
   * @return hasCredentials
   */
  @javax.annotation.Nullable
  public Boolean getHasCredentials() {
    return hasCredentials;
  }

  public void setHasCredentials(@javax.annotation.Nullable Boolean hasCredentials) {
    this.hasCredentials = hasCredentials;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectSmsByoPublic projectSmsByoPublic = (ProjectSmsByoPublic) o;
    return Objects.equals(this.enabled, projectSmsByoPublic.enabled) &&
        Objects.equals(this.provider, projectSmsByoPublic.provider) &&
        Objects.equals(this.defaultFrom, projectSmsByoPublic.defaultFrom) &&
        Objects.equals(this.hasCredentials, projectSmsByoPublic.hasCredentials);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, provider, defaultFrom, hasCredentials);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectSmsByoPublic {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    defaultFrom: ").append(toIndentedString(defaultFrom)).append("\n");
    sb.append("    hasCredentials: ").append(toIndentedString(hasCredentials)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("enabled", "provider", "defaultFrom", "hasCredentials"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ProjectSmsByoPublic
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProjectSmsByoPublic.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ProjectSmsByoPublic is not found in the empty JSON string", ProjectSmsByoPublic.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProjectSmsByoPublic.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ProjectSmsByoPublic` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) && !jsonObj.get("provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider").toString()));
      }
      // validate the optional field `provider`
      if (jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) {
        ProviderEnum.validateJsonElement(jsonObj.get("provider"));
      }
      if ((jsonObj.get("defaultFrom") != null && !jsonObj.get("defaultFrom").isJsonNull()) && !jsonObj.get("defaultFrom").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `defaultFrom` to be a primitive type in the JSON string but got `%s`", jsonObj.get("defaultFrom").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProjectSmsByoPublic.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProjectSmsByoPublic' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProjectSmsByoPublic> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProjectSmsByoPublic.class));

       return (TypeAdapter<T>) new TypeAdapter<ProjectSmsByoPublic>() {
           @Override
           public void write(JsonWriter out, ProjectSmsByoPublic value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProjectSmsByoPublic read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ProjectSmsByoPublic given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProjectSmsByoPublic
   * @throws IOException if the JSON string is invalid with respect to ProjectSmsByoPublic
   */
  public static ProjectSmsByoPublic fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProjectSmsByoPublic.class);
  }

  /**
   * Convert an instance of ProjectSmsByoPublic to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

