/*
 * MUDBASESDK
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support@mudbase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Function execution stats (total, successful, failed, avgExecutionTime, lastExecution).
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-18T02:47:31.275226855Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class FunctionStats {
  public static final String SERIALIZED_NAME_TOTAL_EXECUTIONS = "totalExecutions";
  @SerializedName(SERIALIZED_NAME_TOTAL_EXECUTIONS)
  @javax.annotation.Nullable
  private Integer totalExecutions;

  public static final String SERIALIZED_NAME_SUCCESSFUL_EXECUTIONS = "successfulExecutions";
  @SerializedName(SERIALIZED_NAME_SUCCESSFUL_EXECUTIONS)
  @javax.annotation.Nullable
  private Integer successfulExecutions;

  public static final String SERIALIZED_NAME_FAILED_EXECUTIONS = "failedExecutions";
  @SerializedName(SERIALIZED_NAME_FAILED_EXECUTIONS)
  @javax.annotation.Nullable
  private Integer failedExecutions;

  public static final String SERIALIZED_NAME_AVG_EXECUTION_TIME = "avgExecutionTime";
  @SerializedName(SERIALIZED_NAME_AVG_EXECUTION_TIME)
  @javax.annotation.Nullable
  private BigDecimal avgExecutionTime;

  public static final String SERIALIZED_NAME_LAST_EXECUTION = "lastExecution";
  @SerializedName(SERIALIZED_NAME_LAST_EXECUTION)
  @javax.annotation.Nullable
  private OffsetDateTime lastExecution;

  public FunctionStats() {
  }

  public FunctionStats totalExecutions(@javax.annotation.Nullable Integer totalExecutions) {
    this.totalExecutions = totalExecutions;
    return this;
  }

  /**
   * Get totalExecutions
   * @return totalExecutions
   */
  @javax.annotation.Nullable
  public Integer getTotalExecutions() {
    return totalExecutions;
  }

  public void setTotalExecutions(@javax.annotation.Nullable Integer totalExecutions) {
    this.totalExecutions = totalExecutions;
  }


  public FunctionStats successfulExecutions(@javax.annotation.Nullable Integer successfulExecutions) {
    this.successfulExecutions = successfulExecutions;
    return this;
  }

  /**
   * Get successfulExecutions
   * @return successfulExecutions
   */
  @javax.annotation.Nullable
  public Integer getSuccessfulExecutions() {
    return successfulExecutions;
  }

  public void setSuccessfulExecutions(@javax.annotation.Nullable Integer successfulExecutions) {
    this.successfulExecutions = successfulExecutions;
  }


  public FunctionStats failedExecutions(@javax.annotation.Nullable Integer failedExecutions) {
    this.failedExecutions = failedExecutions;
    return this;
  }

  /**
   * Get failedExecutions
   * @return failedExecutions
   */
  @javax.annotation.Nullable
  public Integer getFailedExecutions() {
    return failedExecutions;
  }

  public void setFailedExecutions(@javax.annotation.Nullable Integer failedExecutions) {
    this.failedExecutions = failedExecutions;
  }


  public FunctionStats avgExecutionTime(@javax.annotation.Nullable BigDecimal avgExecutionTime) {
    this.avgExecutionTime = avgExecutionTime;
    return this;
  }

  /**
   * Get avgExecutionTime
   * @return avgExecutionTime
   */
  @javax.annotation.Nullable
  public BigDecimal getAvgExecutionTime() {
    return avgExecutionTime;
  }

  public void setAvgExecutionTime(@javax.annotation.Nullable BigDecimal avgExecutionTime) {
    this.avgExecutionTime = avgExecutionTime;
  }


  public FunctionStats lastExecution(@javax.annotation.Nullable OffsetDateTime lastExecution) {
    this.lastExecution = lastExecution;
    return this;
  }

  /**
   * Get lastExecution
   * @return lastExecution
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastExecution() {
    return lastExecution;
  }

  public void setLastExecution(@javax.annotation.Nullable OffsetDateTime lastExecution) {
    this.lastExecution = lastExecution;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FunctionStats functionStats = (FunctionStats) o;
    return Objects.equals(this.totalExecutions, functionStats.totalExecutions) &&
        Objects.equals(this.successfulExecutions, functionStats.successfulExecutions) &&
        Objects.equals(this.failedExecutions, functionStats.failedExecutions) &&
        Objects.equals(this.avgExecutionTime, functionStats.avgExecutionTime) &&
        Objects.equals(this.lastExecution, functionStats.lastExecution);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalExecutions, successfulExecutions, failedExecutions, avgExecutionTime, lastExecution);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FunctionStats {\n");
    sb.append("    totalExecutions: ").append(toIndentedString(totalExecutions)).append("\n");
    sb.append("    successfulExecutions: ").append(toIndentedString(successfulExecutions)).append("\n");
    sb.append("    failedExecutions: ").append(toIndentedString(failedExecutions)).append("\n");
    sb.append("    avgExecutionTime: ").append(toIndentedString(avgExecutionTime)).append("\n");
    sb.append("    lastExecution: ").append(toIndentedString(lastExecution)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("totalExecutions", "successfulExecutions", "failedExecutions", "avgExecutionTime", "lastExecution"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FunctionStats
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FunctionStats.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in FunctionStats is not found in the empty JSON string", FunctionStats.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FunctionStats.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `FunctionStats` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FunctionStats.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FunctionStats' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FunctionStats> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FunctionStats.class));

       return (TypeAdapter<T>) new TypeAdapter<FunctionStats>() {
           @Override
           public void write(JsonWriter out, FunctionStats value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FunctionStats read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FunctionStats given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FunctionStats
   * @throws IOException if the JSON string is invalid with respect to FunctionStats
   */
  public static FunctionStats fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FunctionStats.class);
  }

  /**
   * Convert an instance of FunctionStats to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

