/*
 * MUDBASESDK
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@mudbase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mudbase.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RealtimeAnalyticsGetActiveUsers200ResponseUsersInner
 */
public class RealtimeAnalyticsGetActiveUsers200ResponseUsersInnerTest {
    private final RealtimeAnalyticsGetActiveUsers200ResponseUsersInner model = new RealtimeAnalyticsGetActiveUsers200ResponseUsersInner();

    /**
     * Model tests for RealtimeAnalyticsGetActiveUsers200ResponseUsersInner
     */
    @Test
    public void testRealtimeAnalyticsGetActiveUsers200ResponseUsersInner() {
        // TODO: test RealtimeAnalyticsGetActiveUsers200ResponseUsersInner
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'connectedAt'
     */
    @Test
    public void connectedAtTest() {
        // TODO: test connectedAt
    }

    /**
     * Test the property 'socketId'
     */
    @Test
    public void socketIdTest() {
        // TODO: test socketId
    }

}
